### PR TITLE
im back bitches

### PR DESCRIPTION
**Pull request by ajl223**
It’s 🙂 me 😄 baby 👶 kata 🥵I 🌚 have ✨a 🅰️ huge 🦖 diarrhea 💩🤪 if 😉 you 🦶fart 💨 like 🦄 you 🤡 don’t ☠️ care 😳 raise 🗣 your 🧞‍♂️ bog 🤯 roll 🌯 in 🤢 the 👈 air 😌🌈💫💨 pee ⚡️ pee ⚡️ poo 🕴 poo 🕴 wee 🚶‍♂️wee 🚶‍♂️eho 💃 eho 🕺 eh 🌍

### CODE REVIEW

**Comment by ajl223** [comment]
Pee Pee Poo Poo
Baby Kata
A strong, heart felt song words cannot explain. This is truely a masterpiece, a work of art on the topic of baby katas strong shit.

Produced by
Toilette Records

Release Date
July 12, 2015
View All Credits 
1
56.7K
50
15
It's me Baby Kata
I have a huge diarrhea
If you fart like you don't care
Raise your bog rolls in the air

Pee pee poo poo
Wee hee hoo a hoo a
Pee pee poo poo
Wee hee hoo a hoo a

When you take a comfort stop
You feel like you reach the top
Choco balls are gonna pop
Its the sound of the sound of the big flop
Every poop is so fantastic
Every poop is so terrific

Everybody look at me
Im makin a big poopy

Pee pee poo poo
Wee hee hoo a hoo a
Pee pee poo poo
Wee hee hoo a hoo apee pee poo poo
Wee hee hoo a hoo a
Pee pee poo poo
Wee hee hoo a hoo a
Let me show you magic tricks
Brown monkey does gymnastics
Tiny turds or massive bricks
I like to share my poop pics
Every poop is so fantastic
Every poop is so terrific

Are you ready for action
Its time to release the kraken

Pee pee poo poo
Wee hee hoo a hoo a
Pee pee poo poo
Wee hee hoo a hoo apee pee poo poo
Wee hee hoo a hoo a
Pee pee poo poo
Wee hee hoo a hoo a

Come on! Drop it now!

**Comment by ajl223** [comment]
I hate my life what am I doing with my life

**Comment by 0x150** [comment]
what the fuck

**Comment by Saturn5Vfive** [comment]
what is rong w u

**Comment by BobIsMyManager** [comment]
What did he even change? It just looks like he removed a line then added it back again

**Comment by ajl223** [comment]
logo to readme

**Comment by BobIsMyManager** [comment]
Ok

**Pull request merged**
