### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ajl223**

### CODE REVIEW

**Comment by ajl223** [comment]
honestly useless im just bored

**Comment by BobIsMyManager** [comment]
It does this on every os

**Comment by BobIsMyManager** [comment]
What are you talking about

**Comment by aaashleyyyy** [comment]
we are talking about sex

**Comment by ajl223** [comment]
1-3 steps are still on windows acshually 🤓

**Comment by aaashleyyyy** [comment]
you need to die irl

**Comment by BobIsMyManager** [comment]
> 1-3 steps are still on windows acshually 🤓

?

**Comment by aaashleyyyy** [comment]
windows isnt real dumbass

**Comment by BobIsMyManager** [comment]
Those are the only steps

**Comment by aaashleyyyy** [comment]
sex

**Comment by aaashleyyyy** [comment]
i am the sex

**Comment by ajl223** [comment]
saying you are free from doing the steps 1-3 for linux since you are on windows 
windows category in readme has steps 1-3

**Comment by aaashleyyyy** [comment]
rename atomic to sex client

**Comment by BobIsMyManager** [comment]
> saying you are free from doing the steps 1-3 for linux since you are on windows
> windows category in readme has steps 1-3

There is instructions for Linux above, why tf would u put it in the Linux section?

**Comment by aaashleyyyy** [comment]
we need sex client

**Comment by aaashleyyyy** [comment]
pls

**Comment by ajl223** [comment]
> 
> 
> > saying you are free from doing the steps 1-3 for linux since you are on windows
> > windows category in readme has steps 1-3
> 
> There is instructions for Linux above, why tf would u put it in the Windows section?

read the commit

**Comment by 0x150** [comment]
ashley i am actually going to blacklist you from the project if you continue this

**Comment by ajl223** [comment]
lol

**Comment by 0x150** [comment]
also, kinda not needed so

**Comment by aaashleyyyy** [comment]
:joesad:

**Comment by ajl223** [comment]
you sussy baka!

**Comment by BobIsMyManager** [comment]
> > > saying you are free from doing the steps 1-3 for linux since you are on windows
> > > windows category in readme has steps 1-3
> > 
> > 
> > There is instructions for Linux above, why tf would u put it in the Windows section?
> 
> read the commit

### Windows
 The default launcher should already choose java 16 for the runtime, so you're free from steps 1-3
 The default launcher should already choose java 16 for the runtime, so you're free from steps 1-3 on GNU/Linux

**Comment by BobIsMyManager** [comment]
In the windows sectiom

**Comment by BobIsMyManager** [comment]
Instead of the windows one

**Comment by BobIsMyManager** [comment]
*linux

**Comment by BobIsMyManager** [comment]
I am tired

**Comment by ajl223** [comment]
*The default launcher should already choose java 16 for the runtime, so you're free from steps 1-3 since you are not on GNU/Linux

**Comment by BobIsMyManager** [comment]
They are the only steps so who cares

**Comment by 0x150** [comment]
can you all shut the fuck up

**Pull request closed without merging**
